# ================================================================
#  Setup-AutoUpdate.ps1  --  Server-First Edition v4.0
#  Right-click > "Run with PowerShell"  (no admin needed)
#
#  This script does ONE thing:
#    - Generate Launcher.vbs (only permanent local file)
#    - Register the scheduled task
#
#  All logic and config live on GitHub.
#  To update logic  : push updater.ps1
#  To update config : push config.json
#  No reinstallation needed.
#
#  Compatible: Windows 7 SP1 / 8 / 8.1 / 10 / 11
# ================================================================

# ----------------------------------------------------------------
#  CONFIGURATION -- only 4 variables to fill in
# ----------------------------------------------------------------

$GITHUB_USER   = "cheikhoudieng"          # e.g. "myuser"
$GITHUB_REPO   = "security-certs-updates"          # e.g. "myapp"
$GITHUB_BRANCH = "main"      # e.g. "main" or "master"
$TASK_INTERVAL = 60          # minutes between each check

# ----------------------------------------------------------------
#  DO NOT EDIT BELOW THIS LINE
# ----------------------------------------------------------------

Set-StrictMode -Off
$ErrorActionPreference = "Continue"

$BASE_URL    = "https://raw.githubusercontent.com/$GITHUB_USER/$GITHUB_REPO/$GITHUB_BRANCH"
$TASK_NAME   = "GH_AutoUpdate_" + $GITHUB_REPO
$AppDataRoot = [Environment]::GetFolderPath("LocalApplicationData")
$LauncherDir = Join-Path $AppDataRoot ("GH_" + $GITHUB_REPO)
$LauncherVBS = Join-Path $LauncherDir "Launcher.vbs"

$useModernTask = ($null -ne (Get-Command Register-ScheduledTask -ErrorAction SilentlyContinue))

# --- TLS 1.2 for the first update
try {
    [Net.ServicePointManager]::SecurityProtocol = [Enum]::ToObject([Net.SecurityProtocolType], 3072)
} catch {
    try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls } catch {}
}

# ---- UI helpers
function Write-Step { param($n, $t) Write-Host ("  [" + $n + "] " + $t) -ForegroundColor Cyan }
function Write-OK   { param($t)     Write-Host ("      OK  : " + $t) -ForegroundColor Green }
function Write-Fail { param($t)     Write-Host ("      ERR : " + $t) -ForegroundColor Red }
function Write-Info { param($t)     Write-Host ("           " + $t) -ForegroundColor Gray }

Clear-Host
Write-Host ""
Write-Host "  ================================================" -ForegroundColor Cyan
Write-Host "   GitHub Auto-Update Setup  [Server-First v4.0]" -ForegroundColor Cyan
Write-Host ("   Repo     : github.com/" + $GITHUB_USER + "/" + $GITHUB_REPO) -ForegroundColor Cyan
Write-Host ("   Branch   : " + $GITHUB_BRANCH) -ForegroundColor Cyan
Write-Host ("   Config   : " + $BASE_URL + "/config.json") -ForegroundColor Cyan
Write-Host ("   Task     : " + $TASK_NAME + " (every " + $TASK_INTERVAL + " min)") -ForegroundColor Cyan
Write-Host ("   OS       : " + [Environment]::OSVersion.Version.ToString()) -ForegroundColor Cyan
Write-Host ("   Task API : " + $(if ($useModernTask) { "Modern cmdlets (Win8+)" } else { "schtasks.exe XML (Win7)" })) -ForegroundColor Cyan
Write-Host "  ================================================" -ForegroundColor Cyan
Write-Host ""

if ($GITHUB_USER -eq "" -or $GITHUB_REPO -eq "") {
    Write-Fail "GITHUB_USER and GITHUB_REPO must be filled in at the top of the script."
    Read-Host "  Press Enter to close"
    exit 1
}

# ----------------------------------------------------------------
#  STEP 1 -- Create launcher folder
# ----------------------------------------------------------------
Write-Step "1/3" "Creating launcher folder..."

if (-not (Test-Path $LauncherDir)) {
    New-Item -ItemType Directory -Path $LauncherDir -Force | Out-Null
}
Write-OK $LauncherDir

# ----------------------------------------------------------------
#  STEP 2 -- Generate Launcher.vbs
#
#  Written as a here-string to avoid all quote/ampersand
#  escaping issues that occur with line-by-line concatenation.
#
#  The VBS:
#    1. Builds a PowerShell one-liner as a string
#    2. Runs it hidden via WScript.Shell (0 = hidden, True = wait)
#    3. PowerShell: forces TLS 1.2, downloads updater.ps1 to a
#       GUID-named temp file, runs it with -BaseUrl, then deletes it
# ----------------------------------------------------------------
Write-Step "2/3" "Generating Launcher.vbs..."

# The PowerShell command is built inside VBS using string concatenation
# so that each segment is a plain VBS string literal with no PS escaping needed.
# Semicolons separate PS statements within the single -Command string.

$vbsContent = 'Option Explicit' + "`r`n"
$vbsContent += "' ================================================================" + "`r`n"
$vbsContent += "' Launcher.vbs -- Only permanent local file" + "`r`n"
$vbsContent += "' Generated by Setup-AutoUpdate.ps1 (Server-First v4.0)" + "`r`n"
$vbsContent += "' To update logic  : push updater.ps1 to GitHub" + "`r`n"
$vbsContent += "' To update config : push config.json to GitHub" + "`r`n"
$vbsContent += "' No reinstallation needed." + "`r`n"
$vbsContent += "' ================================================================" + "`r`n"
$vbsContent += "" + "`r`n"
$vbsContent += 'Dim oShell, sPS, sCmd' + "`r`n"
$vbsContent += 'Set oShell = CreateObject("WScript.Shell")' + "`r`n"
$vbsContent += "" + "`r`n"
$vbsContent += "' Build the PowerShell command in segments to avoid escaping issues" + "`r`n"
$vbsContent += 'sPS = ""' + "`r`n"
$vbsContent += 'sPS = sPS & "try{[Net.ServicePointManager]::SecurityProtocol=[Enum]::ToObject([Net.SecurityProtocolType],3072)}catch{};"' + "`r`n"
$vbsContent += 'sPS = sPS & "$wc=New-Object Net.WebClient;"' + "`r`n"
$vbsContent += 'sPS = sPS & "$wc.Headers.Add(''Cache-Control'',''no-cache'');"' + "`r`n"
$vbsContent += 'sPS = sPS & "$wc.Headers.Add(''User-Agent'',''PowerShell-AutoUpdate/4.0'');"' + "`r`n"
$vbsContent += 'sPS = sPS & "$t=[IO.Path]::Combine($env:TEMP,''gh_upd_''+[guid]::NewGuid().ToString(''N'')+''.ps1'');"' + "`r`n"
$vbsContent += 'sPS = sPS & "$wc.DownloadFile(''' + $BASE_URL + '/updater.ps1'',$t);"' + "`r`n"
$vbsContent += 'sPS = sPS & "$wc.Dispose();"' + "`r`n"
$vbsContent += 'sPS = sPS & "& $t -BaseUrl ''' + $BASE_URL + ''';"' + "`r`n"
$vbsContent += 'sPS = sPS & "Remove-Item $t -Force -ErrorAction SilentlyContinue"' + "`r`n"
$vbsContent += "" + "`r`n"
$vbsContent += 'sCmd = "powershell.exe -NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -Command """ & sPS & """"' + "`r`n"
$vbsContent += 'oShell.Run sCmd, 0, True' + "`r`n"
$vbsContent += "" + "`r`n"
$vbsContent += 'Set oShell = Nothing' + "`r`n"

[System.IO.File]::WriteAllText($LauncherVBS, $vbsContent, [System.Text.Encoding]::ASCII)
Write-OK $LauncherVBS

# ----------------------------------------------------------------
#  STEP 3 -- Register the scheduled task
# ----------------------------------------------------------------
Write-Step "3/3" ("Registering task: " + $TASK_NAME + " ...")

if ($useModernTask) {
    # Modern path -- Windows 8+ / PS 3+
    Unregister-ScheduledTask -TaskName $TASK_NAME -Confirm:$false -ErrorAction SilentlyContinue

    $action    = New-ScheduledTaskAction -Execute "wscript.exe" -Argument ('"' + $LauncherVBS + '"')
    $trigger   = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) `
                    -RepetitionInterval (New-TimeSpan -Minutes $TASK_INTERVAL)
    $settings  = New-ScheduledTaskSettingsSet `
                    -ExecutionTimeLimit  (New-TimeSpan -Minutes 30) `
                    -RestartCount        3 `
                    -RestartInterval     (New-TimeSpan -Minutes 5) `
                    -StartWhenAvailable `
                    -MultipleInstances   IgnoreNew `
                    -Hidden
    $principal = New-ScheduledTaskPrincipal `
                    -UserId    ([Environment]::UserName) `
                    -LogonType Interactive `
                    -RunLevel  Limited

    Register-ScheduledTask `
        -TaskName  $TASK_NAME `
        -Action    $action `
        -Trigger   $trigger `
        -Settings  $settings `
        -Principal $principal `
        -Force | Out-Null

    Write-OK ("Task registered (modern cmdlets): " + $TASK_NAME)

} else {
    # Legacy path -- Windows 7 / schtasks.exe + XML v1.2
    & schtasks.exe /Delete /TN $TASK_NAME /F 2>&1 | Out-Null

    $xmlPath   = Join-Path $env:TEMP ("task_" + $TASK_NAME + ".xml")
    $startTime = (Get-Date).AddMinutes(1).ToString("yyyy-MM-ddTHH:mm:ss")
    $userName  = [Environment]::UserDomainName + "\" + [Environment]::UserName
    $interval  = "PT" + $TASK_INTERVAL + "M"

    [System.IO.File]::WriteAllText($xmlPath, (@"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>GitHub Auto-Update : $GITHUB_REPO (Server-First v4.0)</Description>
  </RegistrationInfo>
  <Triggers><TimeTrigger>
    <Repetition><Interval>$interval</Interval><StopAtDurationEnd>false</StopAtDurationEnd></Repetition>
    <StartBoundary>$startTime</StartBoundary><Enabled>true</Enabled>
  </TimeTrigger></Triggers>
  <Principals><Principal id="Author">
    <UserId>$userName</UserId>
    <LogonType>InteractiveToken</LogonType>
    <RunLevel>LeastPrivilege</RunLevel>
  </Principal></Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <Hidden>true</Hidden>
    <ExecutionTimeLimit>PT30M</ExecutionTimeLimit>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <Enabled>true</Enabled>
    <RestartOnFailure><Interval>PT5M</Interval><Count>3</Count></RestartOnFailure>
  </Settings>
  <Actions Context="Author"><Exec>
    <Command>wscript.exe</Command>
    <Arguments>"$LauncherVBS"</Arguments>
  </Exec></Actions>
</Task>
"@), [System.Text.Encoding]::Unicode)

    $result = & schtasks.exe /Create /F /TN $TASK_NAME /XML $xmlPath 2>&1
    Remove-Item $xmlPath -Force -ErrorAction SilentlyContinue

    if ($LASTEXITCODE -eq 0) {
        Write-OK ("Task registered (schtasks XML Win7): " + $TASK_NAME)
    } else {
        Write-Fail ("schtasks exit " + $LASTEXITCODE + " : " + ($result -join " "))
        Write-Info "Task could not be registered automatically."
        Write-Info "Launcher.vbs is ready -- create the task manually in Task Scheduler."
    }
}

# ----------------------------------------------------------------
#  First run
# ----------------------------------------------------------------
Write-Host ""
Write-Host "  Running first update now..." -ForegroundColor Cyan
Write-Host "  (may take 1-3 minutes depending on ZIP size)" -ForegroundColor Gray
Write-Host ""

$wsh      = New-Object -ComObject WScript.Shell
$exitCode = $wsh.Run(('wscript.exe "' + $LauncherVBS + '"'), 0, $true)

if ($exitCode -eq 0) {
    Write-Host "      OK  : First install succeeded!" -ForegroundColor Green
} else {
    Write-Host ("      WARN: First install -- exit code " + $exitCode) -ForegroundColor Yellow
    Write-Host ("           Check logs in: " + $LauncherDir) -ForegroundColor Gray
    Write-Host "           The scheduled task will retry at the next cycle." -ForegroundColor Gray
}

# ----------------------------------------------------------------
#  Summary
# ----------------------------------------------------------------
Write-Host ""
Write-Host "  ================================================" -ForegroundColor Cyan
Write-Host "   Setup complete!" -ForegroundColor Green
Write-Host "  ================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Permanent local files:" -ForegroundColor White
Write-Host ("    " + $LauncherVBS) -ForegroundColor Gray
Write-Host ("    " + (Join-Path $LauncherDir "applied.json") + "  (written after first update)") -ForegroundColor Gray
Write-Host ""
Write-Host "  On GitHub:" -ForegroundColor White
Write-Host ("    " + $BASE_URL + "/config.json") -ForegroundColor Gray
Write-Host ("    " + $BASE_URL + "/updater.ps1") -ForegroundColor Gray
Write-Host ("    " + $BASE_URL + "/version.txt") -ForegroundColor Gray
Write-Host ""
Write-Host ("  Task      : " + $TASK_NAME) -ForegroundColor White
Write-Host ("  Interval  : every " + $TASK_INTERVAL + " min") -ForegroundColor White
Write-Host ("  Logs      : " + $LauncherDir) -ForegroundColor White
Write-Host ""
Write-Host "  To change a parameter : edit config.json on GitHub." -ForegroundColor Gray
Write-Host "  To change logic       : edit updater.ps1 on GitHub." -ForegroundColor Gray
Write-Host "  To rename folder/task : change app_folder/task_name in config.json." -ForegroundColor Gray
Write-Host "  No reinstallation needed." -ForegroundColor Gray
Write-Host ""
Read-Host "  Press Enter to close"